version: "3.9"

services:
  mongodb:
    build:
      context: ./src/mongodb
      dockerfile: Dockerfile
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: database
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./mongo-data:/data/db
      - ./transcriptions.json:/docker-entrypoint-initdb.d/transcriptions.json

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  logger-service:
    build:
      context: ./src/logger-service
      dockerfile: Dockerfile
    container_name: logger-service
    depends_on:
      - mongodb
      - rabbitmq
      - orchestrator-service

  orchestrator-service:
    build:
      context: ./src/orchestrator-service
      dockerfile: Dockerfile
    container_name: orchestrator-service
    depends_on:
      - mongodb
      - rabbitmq
    ports:
      - "8080:8080"
    volumes:
      - shared-data:/shared

  summary-service:
    build:
      context: ./src/summary-service
      dockerfile: Dockerfile
    container_name: summary-service
    depends_on:
      - mongodb
      - rabbitmq
      - orchestrator-service
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}

  transcription-service:
    build:
      context: ./src/transcription-service
      dockerfile: Dockerfile
    container_name: transcription-service
    depends_on:
      - mongodb
      - rabbitmq
      - orchestrator-service
    environment:
      - HF_TOKEN=${HF_TOKEN}
    volumes:
      - shared-data:/shared

volumes:
  shared-data:
